importing numpy library

In [1]:
import numpy as np

Matrix Addition:

two matrices can be added only if they have the same shape

In [5]:
#creating two matrices
a=np.array([[2,3],[10,5]])
b=np.array([[10,5],[20,4]])


In [9]:
print(a)
a.shape

[[ 2  3]
 [10  5]]


(2, 2)

In [10]:
print(b)
b.shape

[[10  5]
 [20  4]]


(2, 2)

Adding two matrices

In [11]:
sum=a+b
print(sum)
sum.shape


[[12  8]
 [30  9]]


(2, 2)

In [15]:
#creating a matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(20,size=(3,3))

In [16]:
print(matrix_1)

[[0 5 4]
 [2 8 2]
 [6 3 3]]


In [17]:
print(matrix_2)

[[10  4  1]
 [19 15 13]
 [ 4 17  8]]


In [18]:
sum=np.add(matrix_1,matrix_2)
print(sum)

[[10  9  5]
 [21 23 15]
 [10 20 11]]


In [21]:
matrix_3=np.random.randint(10,size=(3,3))
matrix_4=np.random.randint(20,size=(3,4))

In [22]:
sum_2=np.add(matrix_3,matrix_4)
print(sum_2)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

we get this error because shape of matrix_3 and matrix_4 are different

Matrix subtraction

In [23]:
a=np.array([[2,3],[10,5]])
b=np.array([[10,5],[20,4]])

In [26]:
print(a)

[[ 2  3]
 [10  5]]


In [27]:
print(b)

[[10  5]
 [20  4]]


In [25]:
difference=a-b
print(difference)

[[ -8  -2]
 [-10   1]]


In [28]:
matrix_3=np.random.randint(10,size=(3,3))
matrix_4=np.random.randint(20,size=(3,3))

In [29]:
print(matrix_3)

[[5 7 8]
 [2 3 8]
 [5 6 2]]


In [30]:
print(matrix_4)

[[ 3  9  4]
 [12 15  3]
 [10 17 15]]


In [34]:
diff=np.subtract(matrix_3,matrix_4)
print(diff)

[[  2  -2   4]
 [-10 -12   5]
 [ -5 -11 -13]]


Multiplying a matrix by a scalar

In [35]:
x=5
y=np.random.randint(10,size=(4,4))
print(y)

[[6 1 9 8]
 [9 0 7 8]
 [9 1 9 3]
 [2 8 6 4]]


In [36]:
product=np.multiply(x,y)
print(product)

[[30  5 45 40]
 [45  0 35 40]
 [45  5 45 15]
 [10 40 30 20]]


Multiplying 2 matrices

In [37]:
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,4))

In [38]:
print(matrix_3)

[[1 4 3]
 [1 2 2]
 [1 2 2]]


In [39]:
print(matrix_4)

[[1 4 3 1]
 [4 0 1 3]
 [4 2 3 1]]


In [40]:
product=np.dot(matrix_3,matrix_4)
print(product)

[[29 10 16 16]
 [17  8 11  9]
 [17  8 11  9]]


In [41]:
product.shape

(3, 4)

In [42]:
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(4,4))

In [43]:
product=np.dot(matrix_3,matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

Element wise matrix multiplication

In [47]:
matrix_3=np.random.randint(5,size=(3,3))
matrix_4=np.random.randint(5,size=(3,3))

In [48]:
print(matrix_3)

[[1 0 4]
 [1 1 1]
 [0 1 2]]


In [49]:
print(matrix_4)

[[0 4 1]
 [1 0 1]
 [3 1 1]]


In [50]:
mul=np.multiply(matrix_3,matrix_4)
print(mul)

[[0 0 4]
 [1 0 1]
 [0 1 2]]
