In [2]:
import numpy as np

Creating a matrix using numpy

In [3]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [5]:
matrix_1.shape

(2, 2)

In [6]:
matrix_2=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(matrix_2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
matrix_2.shape

(3, 3)

creating a matrices with random values

In [8]:
matrix_3=np.random.rand(3,3)
print(matrix_3)

[[0.39491769 0.80388261 0.78571115]
 [0.42230765 0.22905489 0.30243378]
 [0.10872827 0.75323151 0.25918756]]


In [9]:
#creating a matrix with random integers
random_integer_matrix=np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[91 72 20 83 32]
 [83 62 56 13 80]
 [30 73 75 48 36]
 [ 3 75 47 67  3]]


Matrix with all the values as one

In [10]:
matrix_4=np.ones((2,3))  #floating values
print(matrix_4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
matrix_4=np.ones((2,3),dtype=int)  #integer values
print(matrix_4)

[[1 1 1]
 [1 1 1]]


Null matrix or Zero matrix

In [12]:
matrix_5=np.zeros((2,3))  #floating values
print(matrix_5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
matrix_5=np.zeros((2,3),dtype=int)  #integer values
print(matrix_5)

[[0 0 0]
 [0 0 0]]


Identity Matrix

In [15]:
identity_matrix=np.eye(3)  #floating values
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
identity_matrix=np.eye(3,dtype=int)  #integer values
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Transpose of a Matrix

In [19]:
#matrix with random integer values
matrix=np.random.randint(100,size=(4,5))
print(matrix)

[[44 66 59 50 73]
 [15 36 98 71 13]
 [65 68 70 38 95]
 [27 88 95 65 37]]


In [20]:
transpose_matrix=np.transpose(matrix)
print(transpose_matrix)

[[44 15 65 27]
 [66 36 68 88]
 [59 98 70 95]
 [50 71 38 65]
 [73 13 95 37]]
